### ISSUE TITLE
izin fork

### ISSUE THREAD

**Issue by adhiariyadi** [baydim/gstore#1]
bang mana project nya kok cuma ada readme aja :)

**Comment by baydim** [comment]
Masih hidden ya

Pada tanggal Jum, 26 Mar 2021 14.28, Adhi Ariyadi ***@***.***>
menulis:

**Comment by baydim** [comment]
Udah tak buka nih

Pada tanggal Jum, 26 Mar 2021 14.28, Adhi Ariyadi ***@***.***>
menulis:

**Comment by adhiariyadi** [comment]
ini gk ada panduan cara installnya bang?

**Comment by baydim** [comment]
Itu ada direadme nya..ikut aja entar ketemu

Pada tanggal Jum, 26 Mar 2021 14.45, Adhi Ariyadi ***@***.***>
menulis:

**Comment by adhiariyadi** [comment]
ok ok makasih

**Comment by baydim** [comment]
Btw udah ada versi ke dua tapi belum aku publis

Pada tanggal Jum, 26 Mar 2021 14.50, Adhi Ariyadi ***@***.***>
menulis:

**Comment by adhiariyadi** [comment]
di tunggu bang

**Comment by baydim** [comment]
Siapp

Pada tanggal Jum, 26 Mar 2021 14.52, Adhi Ariyadi ***@***.***>
menulis:
